blank_issues_enabled: true
contact_links:
  - name: 💬 Discussões gerais
    url: https://github.com/qway-tech/qats/discussions
    about: Perguntas abertas e conversas que não se encaixam em uma issue específica
